[package]
name = "bhci"
description = "Basel Haskell Compiler Interactive REPL"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bhci"
path = "src/main.rs"

[dependencies]
bhc-span = { workspace = true }
bhc-intern = { workspace = true }
bhc-diagnostics = { workspace = true }
bhc-lexer = { workspace = true }
bhc-ast = { workspace = true }
bhc-parser = { workspace = true }
bhc-session = { workspace = true }

clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
